# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a currupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

#  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [2]:
#Your code here
import pandas as pd
zip_codes_df = pd.read_csv("./Data/Zipcode_Demos.csv", skiprows=47)

In [3]:
zip_codes_df.head()

,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,48,10001,44,22,0.50,22,0.50,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
1,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
2,50,10003,1,1,1.00,0,0.00,0,0,1,...,1,100,0,0.00,1,1.00,0,0,1,100
3,51,10004,0,0,0.00,0,0.00,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,52,10005,2,2,1.00,0,0.00,0,0,2,...,2,100,0,0.00,2,1.00,0,0,2,100

In [4]:
zip_codes_df.drop('47', axis=1, inplace=True)

In [29]:
zip_codes_df.describe()

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.0,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.0,10.000000,10.000000
mean,10005.800000,9.400000,4.800000,0.404000,4.600000,0.396000,0.0,0.0,9.400000,80.000000,...,9.400000,80.000000,2.300000,0.151000,7.100000,0.649000,0.0,0.0,9.400000,80.000000
std,3.425395,16.098309,8.350649,0.403766,7.820202,0.401558,0.0,0.0,16.098309,42.163702,...,16.098309,42.163702,6.254776,0.329661,11.618472,0.468341,0.0,0.0,16.098309,42.163702
min,10001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
25%,10003.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1.000000,100.000000,...,1.000000,100.000000,0.000000,0.000000,0.250000,0.137500,0.0,0.0,1.000000,100.000000
50%,10005.500000,2.000000,1.500000,0.415000,1.000000,0.395000,0.0,0.0,2.000000,100.000000,...,2.000000,100.000000,0.000000,0.000000,2.000000,0.970000,0.0,0.0,2.000000,100.000000
75%,10008.500000,5.250000,2.000000,0.637500,3.500000,0.627500,0.0,0.0,5.250000,100.000000,...,5.250000,100.000000,0.750000,0.045000,5.250000,1.000000,0.0,0.0,5.250000,100.000000
max,10011.000000,44.000000,22.000000,1.000000,22.000000,1.000000,0.0,0.0,44.000000,100.000000,...,44.000000,100.000000,20.000000,1.000000,33.000000,1.000000,0.0,0.0,44.000000,100.000000

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [34]:
#Hint: here's a useful programming pattern to use.
try:
    #do something
    df = pd.read_csv("./Data/Yelp_Reviews_Corrupt.csv",  error_bad_lines=False)
except Exception as e:
    #handle your exception e
    print(e)

b'Skipping line 2331: expected 10 fields, saw 11\nSkipping line 2340: expected 10 fields, saw 12\nSkipping line 2341: expected 10 fields, saw 13\nSkipping line 2343: expected 10 fields, saw 18\nSkipping line 2349: expected 10 fields, saw 12\nSkipping line 2350: expected 10 fields, saw 16\nSkipping line 2352: expected 10 fields, saw 12\nSkipping line 2358: expected 10 fields, saw 13\nSkipping line 2359: expected 10 fields, saw 11\nSkipping line 2379: expected 10 fields, saw 11\nSkipping line 2381: expected 10 fields, saw 12\nSkipping line 2382: expected 10 fields, saw 12\nSkipping line 2384: expected 10 fields, saw 11\nSkipping line 2386: expected 10 fields, saw 12\nSkipping line 2388: expected 10 fields, saw 12\nSkipping line 2389: expected 10 fields, saw 13\nSkipping line 2392: expected 10 fields, saw 15\nSkipping line 2393: expected 10 fields, saw 18\nSkipping line 2394: expected 10 fields, saw 15\nSkipping line 2407: expected 10 fields, saw 12\nSkipping line 2427: expected 10 fields, saw 11\nSkipping line 2430: expected 10 fields, saw 12\nSkipping line 2438: expected 10 fields, saw 17\nSkipping line 2439: expected 10 fields, saw 11\nSkipping line 2440: expected 10 fields, saw 11\nSkipping line 2441: expected 10 fields, saw 11\nSkipping line 2442: expected 10 fields, saw 12\nSkipping line 2445: expected 10 fields, saw 13\nSkipping line 2446: expected 10 fields, saw 12\nSkipping line 2473: expected 10 fields, saw 13\nSkipping line 2474: expected 10 fields, saw 11\nSkipping line 2475: expected 10 fields, saw 12\nSkipping line 2485: expected 10 fields, saw 12\nSkipping line 2487: expected 10 fields, saw 15\nSkipping line 2488: expected 10 fields, saw 11\nSkipping line 2496: expected 10 fields, saw 20\nSkipping line 2504: expected 10 fields, saw 13\nSkipping line 2505: expected 10 fields, saw 13\nSkipping line 2507: expected 10 fields, saw 11\nSkipping line 2521: expected 10 fields, saw 15\nSkipping line 2522: expected 10 fields, saw 12\nSkipping line 2525: expected 10 fields, saw 13\nSkipping line 2533: expected 10 fields, saw 12\nSkipping line 2548: expected 10 fields, saw 11\nSkipping line 2561: expected 10 fields, saw 14\nSkipping line 2563: expected 10 fields, saw 15\nSkipping line 2564: expected 10 fields, saw 15\nSkipping line 2565: expected 10 fields, saw 11\nSkipping line 2571: expected 10 fields, saw 13\nSkipping line 2574: expected 10 fields, saw 20\nSkipping line 2575: expected 10 fields, saw 14\nSkipping line 2577: expected 10 fields, saw 12\nSkipping line 2583: expected 10 fields, saw 12\nSkipping line 2584: expected 10 fields, saw 13\nSkipping line 2621: expected 10 fields, saw 15\nSkipping line 2622: expected 10 fields, saw 12\nSkipping line 2631: expected 10 fields, saw 13\nSkipping line 2632: expected 10 fields, saw 12\nSkipping line 2633: expected 10 fields, saw 12\nSkipping line 2636: expected 10 fields, saw 11\nSkipping line 2640: expected 10 fields, saw 11\nSkipping line 2641: expected 10 fields, saw 11\nSkipping line 2674: expected 10 fields, saw 11\nSkipping line 2676: expected 10 fields, saw 16\nSkipping line 2706: expected 10 fields, saw 14\nSkipping line 2708: expected 10 fields, saw 12\nSkipping line 2712: expected 10 fields, saw 17\nSkipping line 2714: expected 10 fields, saw 13\nSkipping line 2715: expected 10 fields, saw 13\nSkipping line 2737: expected 10 fields, saw 11\nSkipping line 2746: expected 10 fields, saw 11\nSkipping line 2752: expected 10 fields, saw 11\nSkipping line 2753: expected 10 fields, saw 15\nSkipping line 2754: expected 10 fields, saw 11\nSkipping line 2758: expected 10 fields, saw 15\nSkipping line 2761: expected 10 fields, saw 12\nSkipping line 2762: expected 10 fields, saw 23\nSkipping line 2767: expected 10 fields, saw 11\nSkipping line 2769: expected 10 fields, saw 13\nSkipping line 2771: expected 10 fields, saw 11\nSkipping line 2785: expected 10 fields, saw 14\nSkipping line 2787: expected 10 fields, saw 12\nSkipping line 2810: expected 10 fields, saw 19\nSkipping line 2817: expected 10 fields, saw 11\nSkipping line 2831: expected 10 fields, saw 11\nSkipping line 2835: expected 10 fields, saw 13\nSkipping line 2837: expected 10 fields, saw 25\nSkipping line 2841: expected 10 fields, saw 13\nSkipping line 2842: expected 10 fields, saw 11\nSkipping line 2848: expected 10 fields, saw 11\nSkipping line 2885: expected 10 fields, saw 13\nSkipping line 2901: expected 10 fields, saw 11\nSkipping line 2902: expected 10 fields, saw 12\nSkipping line 2903: expected 10 fields, saw 11\nSkipping line 2922: expected 10 fields, saw 11\nSkipping line 2923: expected 10 fields, saw 12\nSkipping line 2924: expected 10 fields, saw 11\nSkipping line 2931: expected 10 fields, saw 12\nSkipping line 2940: expected 10 fields, saw 11\nSkipping line 2955: expected 10 fields, saw 17\nSkipping line 2958: expected 10 fields, saw 11\nSkipping line 2971: expected 10 fields, saw 12\nSkipping line 2972: expected 10 fields, saw 11\nSkipping line 2995: expected 10 fields, saw 12\nSkipping line 2998: expected 10 fields, saw 13\nSkipping line 2999: expected 10 fields, saw 14\nSkipping line 3007: expected 10 fields, saw 16\nSkipping line 3019: expected 10 fields, saw 11\nSkipping line 3035: expected 10 fields, saw 11\nSkipping line 3064: expected 10 fields, saw 11\nSkipping line 3066: expected 10 fields, saw 19\nSkipping line 3069: expected 10 fields, saw 11\nSkipping line 3079: expected 10 fields, saw 13\nSkipping line 3080: expected 10 fields, saw 12\nSkipping line 3086: expected 10 fields, saw 17\nSkipping line 3092: expected 10 fields, saw 11\nSkipping line 3106: expected 10 fields, saw 11\nSkipping line 3117: expected 10 fields, saw 12\nSkipping line 3120: expected 10 fields, saw 11\nSkipping line 3122: expected 10 fields, saw 16\nSkipping line 3125: expected 10 fields, saw 29\nSkipping line 3126: expected 10 fields, saw 11\nSkipping line 3127: expected 10 fields, saw 14\nSkipping line 3152: expected 10 fields, saw 12\nSkipping line 3159: expected 10 fields, saw 24\nSkipping line 3169: expected 10 fields, saw 15\nSkipping line 3221: expected 10 fields, saw 14\nSkipping line 3234: expected 10 fields, saw 13\nSkipping line 3235: expected 10 fields, saw 12\nSkipping line 3253: expected 10 fields, saw 11\nSkipping line 3257: expected 10 fields, saw 13\nSkipping line 3274: expected 10 fields, saw 12\nSkipping line 3283: expected 10 fields, saw 12\nSkipping line 3288: expected 10 fields, saw 11\nSkipping line 3289: expected 10 fields, saw 14\nSkipping line 3290: expected 10 fields, saw 15\nSkipping line 3308: expected 10 fields, saw 11\nSkipping line 3309: expected 10 fields, saw 13\nSkipping line 3310: expected 10 fields, saw 13\nSkipping line 3325: expected 10 fields, saw 13\nSkipping line 3329: expected 10 fields, saw 11\nSkipping line 3338: expected 10 fields, saw 17\nSkipping line 3339: expected 10 fields, saw 11\nSkipping line 3344: expected 10 fields, saw 15\nSkipping line 3350: expected 10 fields, saw 11\nSkipping line 3361: expected 10 fields, saw 15\nSkipping line 3362: expected 10 fields, saw 11\nSkipping line 3375: expected 10 fields, saw 13\nSkipping line 3376: expected 10 fields, saw 12\nSkipping line 3377: expected 10 fields, saw 12\nSkipping line 3378: expected 10 fields, saw 16\nSkipping line 3384: expected 10 fields, saw 14\nSkipping line 3385: expected 10 fields, saw 17\nSkipping line 3386: expected 10 fields, saw 11\nSkipping line 3403: expected 10 fields, saw 14\nSkipping line 3404: expected 10 fields, saw 13\nSkipping line 3405: expected 10 fields, saw 18\nSkipping line 3413: expected 10 fields, saw 16\nSkipping line 3414: expected 10 fields, saw 13\nSkipping line 3422: expected 10 fields, saw 11\nSkipping line 3423: expected 10 fields, saw 13\nSkipping line 3435: expected 10 fields, saw 13\nSkipping line 3437: expected 10 fields, saw 14\nSkipping line 3438: expected 10 fields, saw 13\nSkipping line 3439: expected 10 fields, saw 11\nSkipping line 3442: expected 10 fields, saw 11\nSkipping line 3443: expected 10 fields, saw 11\nSkipping line 3467: expected 10 fields, saw 12\nSkipping line 3468: expected 10 fields, saw 29\nSkipping line 3470: expected 10 fields, saw 12\nSkipping line 3471: expected 10 fields, saw 24\nSkipping line 3474: expected 10 fields, saw 17\nSkipping line 3475: expected 10 fields, saw 11\nSkipping line 3476: expected 10 fields, saw 12\nSkipping line 3478: expected 10 fields, saw 14\nSkipping line 3479: expected 10 fields, saw 17\nSkipping line 3480: expected 10 fields, saw 11\nSkipping line 3498: expected 10 fields, saw 15\nSkipping line 3512: expected 10 fields, saw 16\nSkipping line 3513: expected 10 fields, saw 13\nSkipping line 3514: expected 10 fields, saw 13\nSkipping line 3515: expected 10 fields, saw 12\nSkipping line 3516: expected 10 fields, saw 14\nSkipping line 3519: expected 10 fields, saw 15\nSkipping line 3521: expected 10 fields, saw 13\nSkipping line 3522: expected 10 fields, saw 17\nSkipping line 3523: expected 10 fields, saw 11\nSkipping line 3529: expected 10 fields, saw 12\nSkipping line 3530: expected 10 fields, saw 23\nSkipping line 3531: expected 10 fields, saw 13\nSkipping line 3532: expected 10 fields, saw 12\nSkipping line 3537: expected 10 fields, saw 13\nSkipping line 3538: expected 10 fields, saw 26\nSkipping line 3540: expected 10 fields, saw 12\nSkipping line 3559: expected 10 fields, saw 13\nSkipping line 3561: expected 10 fields, saw 11\nSkipping line 3565: expected 10 fields, saw 12\nSkipping line 3566: expected 10 fields, saw 25\nSkipping line 3567: expected 10 fields, saw 11\nSkipping line 3568: expected 10 fields, saw 21\nSkipping line 3591: expected 10 fields, saw 12\nSkipping line 3592: expected 10 fields, saw 12\nSkipping line 3595: expected 10 fields, saw 14\nSkipping line 3615: expected 10 fields, saw 12\nSkipping line 3627: expected 10 fields, saw 12\nSkipping line 3634: expected 10 fields, saw 17\nSkipping line 3641: expected 10 fields, saw 11\nSkipping line 3652: expected 10 fields, saw 12\nSkipping line 3653: expected 10 fields, saw 13\nSkipping line 3656: expected 10 fields, saw 15\nSkipping line 3657: expected 10 fields, saw 12\nSkipping line 3658: expected 10 fields, saw 22\nSkipping line 3672: expected 10 fields, saw 11\nSkipping line 3713: expected 10 fields, saw 19\nSkipping line 3723: expected 10 fields, saw 11\nSkipping line 3725: expected 10 fields, saw 13\nSkipping line 3726: expected 10 fields, saw 14\nSkipping line 3728: expected 10 fields, saw 12\nSkipping line 3733: expected 10 fields, saw 14\nSkipping line 3734: expected 10 fields, saw 12\nSkipping line 3735: expected 10 fields, saw 15\nSkipping line 3740: expected 10 fields, saw 11\nSkipping line 3749: expected 10 fields, saw 12\nSkipping line 3755: expected 10 fields, saw 11\nSkipping line 3756: expected 10 fields, saw 12\nSkipping line 3762: expected 10 fields, saw 11\nSkipping line 3768: expected 10 fields, saw 13\nSkipping line 3776: expected 10 fields, saw 12\nSkipping line 3797: expected 10 fields, saw 11\nSkipping line 3799: expected 10 fields, saw 11\nSkipping line 3805: expected 10 fields, saw 12\nSkipping line 3806: expected 10 fields, saw 12\nSkipping line 3833: expected 10 fields, saw 12\nSkipping line 3844: expected 10 fields, saw 22\nSkipping line 3845: expected 10 fields, saw 12\nSkipping line 3864: expected 10 fields, saw 19\nSkipping line 3877: expected 10 fields, saw 11\nSkipping line 3884: expected 10 fields, saw 13\nSkipping line 3887: expected 10 fields, saw 18\nSkipping line 3889: expected 10 fields, saw 11\nSkipping line 3903: expected 10 fields, saw 13\nSkipping line 3908: expected 10 fields, saw 12\nSkipping line 3917: expected 10 fields, saw 12\nSkipping line 3918: expected 10 fields, saw 12\nSkipping line 3919: expected 10 fields, saw 17\nSkipping line 3926: expected 10 fields, saw 13\nSkipping line 3927: expected 10 fields, saw 12\nSkipping line 3928: expected 10 fields, saw 11\nSkipping line 3946: expected 10 fields, saw 12\nSkipping line 3953: expected 10 fields, saw 12\nSkipping line 3954: expected 10 fields, saw 11\nSkipping line 3955: expected 10 fields, saw 11\nSkipping line 3956: expected 10 fields, saw 14\nSkipping line 3957: expected 10 fields, saw 11\nSkipping line 3959: expected 10 fields, saw 17\nSkipping line 3967: expected 10 fields, saw 16\nSkipping line 3975: expected 10 fields, saw 11\nSkipping line 3976: expected 10 fields, saw 12\nSkipping line 3981: expected 10 fields, saw 14\nSkipping line 3994: expected 10 fields, saw 14\nSkipping line 3997: expected 10 fields, saw 11\nSkipping line 4004: expected 10 fields, saw 11\nSkipping line 4014: expected 10 fields, saw 12\nSkipping line 4015: expected 10 fields, saw 12\nSkipping line 4020: expected 10 fields, saw 11\nSkipping line 4035: expected 10 fields, saw 11\nSkipping line 4041: expected 10 fields, saw 16\nSkipping line 4042: expected 10 fields, saw 12\nSkipping line 4050: expected 10 fields, saw 20\nSkipping line 4051: expected 10 fields, saw 11\nSkipping line 4052: expected 10 fields, saw 13\nSkipping line 4054: expected 10 fields, saw 11\nSkipping line 4055: expected 10 fields, saw 12\nSkipping line 4064: expected 10 fields, saw 11\nSkipping line 4066: expected 10 fields, saw 11\nSkipping line 4067: expected 10 fields, saw 14\nSkipping line 4068: expected 10 fields, saw 11\nSkipping line 4069: expected 10 fields, saw 11\nSkipping line 4070: expected 10 fields, saw 11\nSkipping line 4072: expected 10 fields, saw 11\nSkipping line 4090: expected 10 fields, saw 15\nSkipping line 4091: expected 10 fields, saw 14\nSkipping line 4107: expected 10 fields, saw 13\nSkipping line 4119: expected 10 fields, saw 13\nSkipping line 4120: expected 10 fields, saw 17\nSkipping line 4121: expected 10 fields, saw 11\nSkipping line 4122: expected 10 fields, saw 12\nSkipping line 4126: expected 10 fields, saw 12\nSkipping line 4127: expected 10 fields, saw 11\nSkipping line 4130: expected 10 fields, saw 18\nSkipping line 4131: expected 10 fields, saw 12\nSkipping line 4132: expected 10 fields, saw 12\nSkipping line 4138: expected 10 fields, saw 12\nSkipping line 4140: expected 10 fields, saw 12\nSkipping line 4170: expected 10 fields, saw 13\nSkipping line 4173: expected 10 fields, saw 17\nSkipping line 4180: expected 10 fields, saw 13\nSkipping line 4197: expected 10 fields, saw 13\nSkipping line 4214: expected 10 fields, saw 16\nSkipping line 4242: expected 10 fields, saw 17\nSkipping line 4249: expected 10 fields, saw 11\nSkipping line 4250: expected 10 fields, saw 22\nSkipping line 4257: expected 10 fields, saw 11\nSkipping line 4258: expected 10 fields, saw 11\nSkipping line 4259: expected 10 fields, saw 12\nSkipping line 4261: expected 10 fields, saw 13\nSkipping line 4267: expected 10 fields, saw 11\nSkipping line 4268: expected 10 fields, saw 14\nSkipping line 4277: expected 10 fields, saw 11\nSkipping line 4282: expected 10 fields, saw 20\nSkipping line 4283: expected 10 fields, saw 17\nSkipping line 4285: expected 10 fields, saw 14\nSkipping line 4286: expected 10 fields, saw 18\nSkipping line 4288: expected 10 fields, saw 11\nSkipping line 4305: expected 10 fields, saw 12\nSkipping line 4308: expected 10 fields, saw 15\nSkipping line 4310: expected 10 fields, saw 12\nSkipping line 4312: expected 10 fields, saw 12\nSkipping line 4313: expected 10 fields, saw 11\nSkipping line 4314: expected 10 fields, saw 12\nSkipping line 4324: expected 10 fields, saw 17\nSkipping line 4329: expected 10 fields, saw 12\nSkipping line 4330: expected 10 fields, saw 17\nSkipping line 4336: expected 10 fields, saw 12\nSkipping line 4352: expected 10 fields, saw 11\nSkipping line 4353: expected 10 fields, saw 13\nSkipping line 4375: expected 10 fields, saw 11\nSkipping line 4377: expected 10 fields, saw 12\nSkipping line 4378: expected 10 fields, saw 12\nSkipping line 4383: expected 10 fields, saw 11\nSkipping line 4409: expected 10 fields, saw 15\nSkipping line 4418: expected 10 fields, saw 11\nSkipping line 4419: expected 10 fields, saw 11\nSkipping line 4421: expected 10 fields, saw 13\nSkipping line 4443: expected 10 fields, saw 12\nSkipping line 4445: expected 10 fields, saw 13\nSkipping line 4450: expected 10 fields, saw 11\nSkipping line 4452: expected 10 fields, saw 12\nSkipping line 4455: expected 10 fields, saw 12\nSkipping line 4456: expected 10 fields, saw 11\nSkipping line 4464: expected 10 fields, saw 14\nSkipping line 4487: expected 10 fields, saw 12\nSkipping line 4494: expected 10 fields, saw 15\nSkipping line 4495: expected 10 fields, saw 13\nSkipping line 4503: expected 10 fields, saw 11\nSkipping line 4504: expected 10 fields, saw 11\nSkipping line 4505: expected 10 fields, saw 18\nSkipping line 4527: expected 10 fields, saw 12\nSkipping line 4563: expected 10 fields, saw 11\nSkipping line 4564: expected 10 fields, saw 24\nSkipping line 4565: expected 10 fields, saw 11\nSkipping line 4577: expected 10 fields, saw 12\nSkipping line 4578: expected 10 fields, saw 14\nSkipping line 4589: expected 10 fields, saw 13\nSkipping line 4605: expected 10 fields, saw 15\nSkipping line 4606: expected 10 fields, saw 12\nSkipping line 4607: expected 10 fields, saw 16\nSkipping line 4608: expected 10 fields, saw 19\nSkipping line 4609: expected 10 fields, saw 11\nSkipping line 4626: expected 10 fields, saw 11\nSkipping line 4632: expected 10 fields, saw 13\nSkipping line 4641: expected 10 fields, saw 13\nSkipping line 4658: expected 10 fields, saw 35\nSkipping line 4659: expected 10 fields, saw 12\nSkipping line 4660: expected 10 fields, saw 11\nSkipping line 4665: expected 10 fields, saw 11\nSkipping line 4670: expected 10 fields, saw 14\nSkipping line 4690: expected 10 fields, saw 11\nSkipping line 4695: expected 10 fields, saw 14\nSkipping line 4722: expected 10 fields, saw 13\nSkipping line 4729: expected 10 fields, saw 11\nSkipping line 4730: expected 10 fields, saw 12\nSkipping line 4741: expected 10 fields, saw 12\nSkipping line 4742: expected 10 fields, saw 11\nSkipping line 4764: expected 10 fields, saw 12\nSkipping line 4765: expected 10 fields, saw 13\nSkipping line 4775: expected 10 fields, saw 11\nSkipping line 4776: expected 10 fields, saw 11\nSkipping line 4777: expected 10 fields, saw 11\nSkipping line 4781: expected 10 fields, saw 28\nSkipping line 4782: expected 10 fields, saw 11\nSkipping line 4784: expected 10 fields, saw 11\nSkipping line 4786: expected 10 fields, saw 11\nSkipping line 4787: expected 10 fields, saw 20\nSkipping line 4788: expected 10 fields, saw 11\nSkipping line 4801: expected 10 fields, saw 11\nSkipping line 4802: expected 10 fields, saw 27\nSkipping line 4803: expected 10 fields, saw 11\nSkipping line 4804: expected 10 fields, saw 18\nSkipping line 4806: expected 10 fields, saw 12\nSkipping line 4808: expected 10 fields, saw 16\nSkipping line 4809: expected 10 fields, saw 11\nSkipping line 4825: expected 10 fields, saw 17\nSkipping line 4833: expected 10 fields, saw 11\nSkipping line 4839: expected 10 fields, saw 13\nSkipping line 4840: expected 10 fields, saw 12\nSkipping line 4854: expected 10 fields, saw 11\nSkipping line 4856: expected 10 fields, saw 19\nSkipping line 4859: expected 10 fields, saw 12\nSkipping line 4860: expected 10 fields, saw 11\nSkipping line 4861: expected 10 fields, saw 12\nSkipping line 4862: expected 10 fields, saw 12\nSkipping line 4863: expected 10 fields, saw 11\nSkipping line 4864: expected 10 fields, saw 14\nSkipping line 4865: expected 10 fields, saw 15\nSkipping line 4866: expected 10 fields, saw 11\nSkipping line 4870: expected 10 fields, saw 14\nSkipping line 4878: expected 10 fields, saw 12\nSkipping line 4880: expected 10 fields, saw 14\nSkipping line 4881: expected 10 fields, saw 12\nSkipping line 4891: expected 10 fields, saw 11\nSkipping line 4896: expected 10 fields, saw 11\nSkipping line 4897: expected 10 fields, saw 11\nSkipping line 4909: expected 10 fields, saw 14\nSkipping line 4911: expected 10 fields, saw 11\nSkipping line 4912: expected 10 fields, saw 12\nSkipping line 4918: expected 1

In [35]:
#Your code here
df

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0,HkYqGb0Gplmmk-xlHTRBoA,1,The score should be negative. Its HORRIBLE. Th...,0,NhOc64RsrTT1Dls50yYW8g
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0,RgqWdZA4xR023iP3T6jVfA,5,I went there twice and I am pretty happy with ...,0,NhOc64RsrTT1Dls50yYW8g
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0,51RHs_V_fjuistnuKxNpEg,5,Finally! After trying many Mexican restaurants...,0,5ngpW5tf3ep680eG1HxHzA
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0,alI_kRKyEHfdHibYGgtJbw,1,I have to write a review on the Fractured Prun...,0,Fc_nb6N6Sdurqb-rwsY1Bw
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0,85DRIjwPJOTb4q0qOlBstw,1,I wish i could tell you all about the food but...,1,Fc_nb6N6Sdurqb-rwsY1Bw
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0,GbiLIKmQPVCBtdNkTVdVSA,5,Wonderful! One of my favorite places. BBQ is e...,0,G22ITfVETYHtIhnn5lLRrQ
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0,UaHgsL0xS4UnJ_iKqeOk_w,5,The price is about the same as Quizinos. The s...,0,FjH3TH8OvHGLNEbzdEYlNg
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0,c4zzAD1S6721Fh-acCBy-g,4,The food was ok. You get a lot of food for the...,0,FjH3TH8OvHGLNEbzdEYlNg
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0,TTBwocu2mvqJFJrwmJN0Sw,5,The staff were friendly and helpful. The food ...,1,FjH3TH8OvHGLNEbzdEYlNg
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0,-CresnnXQSHrQ85Ogm-Pqw,5,The staff were very helpful. We painted potter...,0,FjH3TH8OvHGLNEbzdEYlNg
15,32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0,U04YgYr4PiGUxB46J4xapg,2,Limited vegetarian options. Ordered Greek sala...,0,B7Fh30KQT1xPSGt_pIhRRA
16,35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0,s9cpVj40VR_yl0lXbZQe6w,5,I trust my vehicles here. Comparable prices. M...,0,zx_Op2OAOM_fRic9tU-jqA
17,40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0,AJ0IglpYAp2D0daOlVGIdg,1,This place doesn't even deserve 1 star. Horrib...,18,Ka7TIp74VHSa90rfdg4_2g
18,41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0,5D_MsAJHrMa8QKkpE3g1Sg,5,The butter burger was cooked perfectly and jui...,0,Ka7TIp74VHSa90rfdg4_2g
19,42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0,5bWN_IN8MQGjJ6_ZIXffDw,5,Best location ever! I love love love the manag...,0,yyPHK6khPa4-ErV9U32x3A
20,74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0,RW_mYzHYfdqn6g7xVgIcKg,4,This was a real fun time. Lots of laughs and e...,NaN,NaN
21,Food was pretty decent as well. Like the salad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4 stars since I'm bummed there were no mojitos.,0,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0,SLA1YP9doUc8h-6Kd34QmA,1,Horrible. The smart ones have closed their acc...,NaN,NaN
24,Manager doesn't take accountability for the la...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Be smart take you money out and run.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0,qxPiEGIHy5xyVy78avH5Rg,4,Love the 'old school' ambiance. Friendly staff...,NaN,NaN
27,Come for the popcorn and drinks.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0,q6ij-nz5d_hvdjuelho1pQ,5,Better service and much better prices than the...,0,WnM2AmNIint5b5f688nmPg
29,95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0,66FSK2J1uHJqVI1Z8QiFGw,4,I love how they have no rice sushi options. Th...,0,Yy_iGXxLpL6tYDQoE-6XVg
...,...,...,...,...,...,...,...,...,...,...
4005,+kiki burger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,Cons:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,-there isn't one in San Diego!,1,M8KZG9AxSaaJCyRZrHVXzg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4008,Everything else on the menu was enjoyable,with very good portion sizes - small enough t...,the rolls come in 4's,so you can try more than one roll. Another pl...,which I've never seen at AYCE sushi before,along with other jellos (black current and li...,mango pudding and a chef's special.,NaN,NaN,NaN
4009,While pricey,$24.99 on the weekends,I would say that its worth it.,0,hJulW1s6tOBr2NXD9nAoMQ,NaN,NaN,NaN,NaN,NaN
4010,506,RJxkhoGxTsz545_sTlDdFA,0,2014-07-01,0,cEQ9swcZ_L0GMCKI0UtItQ,2,Pad thai (beef),NaN,NaN
4011,- The beef used was tough and chewy. The pad t...,0,UGW-9bbBEB3eP1o6mWD_WA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4012,While Bamburger offers a decent take-out menu,we chose to enjoy their small,but friendly sidewalk patio,right in the middle of restaurant row at Yong...,natural wood and lots of greenery complimenti...,talkative and more than willing to explain th...,as there are many,and recommend some personal favourites.,NaN,NaN
4013,Starting off with drinks,Bamburger serves beer,wine,and old-fashioned Stewart's soda,but what is a burger joint without milkshakes...,including the usual vanilla and chocolate sus...,as well a special flavour each day for the ni...,NaN,NaN,NaN
4014,Bamburger serves up great burgers,fries and shakes at a fairly good price,although if you go a little overboard with th...,you might quickly end up with a $20 burger,without realizing it. The service was friendl...,and the atmosphere was very comfortable and n...,NaN,NaN,NaN,NaN
4015,If you are hunting for a real deal on a burger,Bamburger might not be what you are looking for,but if you are more on the adventurous side,and want to have fun creating your own burger...,Bamburger will deliver.,8,YHWsLBS8jzZiPjKHMFOaAA,NaN,NaN,NaN
4016,4674,4KfDcE9iU2isFpoaKeDpgw,0,2012-06-14,0,rFH9iSvRmdm5LtDdsYwwpA,5,Great place to take your kids and interesting ...,0,9gYbRvijurhrnC6yPRlaUw
4017,3440,nW45ez1L6U4PsYhV1BTrGQ,0,2012-05-19,0,abStF7f3_IyfZmOP82baZQ,5,H&F Jewellery is amazing!,NaN,NaN
4018,I had given my husband some ideas of engagemen...,a friend of ours recommended H&F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4019,The customer service here is great - they are ...,attentive,honest and the prices are very reasonable! My...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4020,We went back for our wedding bands and I worke...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4021,We've recommended 5 other friends to H&F - the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4022,Go to H&F for all your jewellery needs - you w...,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4023,4812,e13SEvJud_vgeDR_doL4sQ,0,2013-03-01,0,lUV1KEm4cl4mluSEFharFQ,4,We loved the food. The service was good and we...,0,NW6gHZ8PlYl1STK1A1Ixeg
4024,564,5XYR6doRa5Nj1JMfSDei6A,1,2016-06-14,0,xlGJkxoIBl8XH8wVsPZpnw,5,Always great friendly service and fresh baked ...,NaN,NaN
4025,Highly recommend the custard cakes they are th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4026,The rice flour cake is also really good and a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4027,The bean cakes are great here too! orange,almond,and a few others I have tried are all good.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4028,Can't go wrong with Nova Era,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4029,3458,aLcFhMe6DDJ430zelCpd2A,0,2013-10-02,0,kwiEG_KCpDB6aK5fTSM7iw,2,We were expecting amazing Thai food after all ...,NaN,NaN
4030,This was disappointing.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4031,First off,it was really awkward sitting on the benches ...,as people walked past us while to wait for ou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4032,Second,when we were seated,it was so loud. It felt like we were in a hig...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4033,Finally - Food was mediocre. I was extremely d...,but it wasn't flavourful.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4034,Wasn't worth the hype,unfortunately.,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN